### ISSUE TITLE
What HTTP request methods to support?

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/http-client#18]
Currently http-client exposes 6 request methods:

https://github.com/fortran-lang/http-client/blob/c1efef853eb1a8ce1ecd1ba8f60f9cc67899bc4c/src/http/http_request.f90#L8-L14

However 3 other methods are defined by HTTP: `CONNECT`, `OPTIONS`, and `TRACE`.

Should they be made available?

We can take one of two paths here:

1. Simply implement them if libcurl supports them; or
2. Don't implement until we have a use-case or a feature request.

**Comment by rajkumardongre** [comment]
While it is true that the `CONNECT`, `OPTIONS`, and `TRACE` HTTP methods are not as commonly used as other methods like `GET`, `POST`, `PUT`, and `DELETE`, i think we can consider them for the sake of API completeness. If these methods are supported by libcurl, it may be worth considering implementing them in our project.

**Comment by milancurcic** [comment]
Let's evaluate the addition of the remaining methods if a need comes up (i.e. if a user opens an issue).
