### ISSUE TITLE
Discussion about the storage of Cookies

### ISSUE THREAD

**Issue by rajkumardongre** [fortran-lang/http-client#22]
To store response cookies, I am considering creating a property called `cookies` inside `http_response` which will be of type `cookie_store_type`. Here is the definition of `cookie_store_type`:
```fortran
 type :: cookie_store_type
    type(fhash_tbl_t), private :: cookies
    type(string_type), private, allocatable :: cookie_names(:)
    integer :: cookie_count = 0	 
 end type cookie_store_type
```
The `cookies` property will maintain a hash table with the **cookie name** as a key of type string. Corresponding to that key, it will have a **`cookie_type` object** that stores all the information about a **single cookie**. Here is the definition of `cookie_type`:
```fortran
type :: cookie_type
    character(:), allocatable :: name, value, path, expires, domain 
    logical :: http_only, same_site, secure
 end type cookie_type
```
Since we can get cookies inside our **response headers**, specifically in the `Set-Cookie` header, I plan to extract the cookies from the `Set-Cookie` header and then parse the cookies to populate the `cookie_type` object. 
Finally, I will store this `cookie_type` object in `response%cookies%cookies` (of type hash map), having the **cookie name** as the key and the `cookie_type` object as the value.

So top level API to access response cookie will be :
```fortran
type(cookie_type) :: cookie
cookie = response%cookies%value('cookie_name')
print *, cookie%name
print *, cookie%value
print *, cookie% path
print *, cookie%expires
print *, cookie%, domain 
```
here `response%cookies%value('cookie_name')` is use to **access a single cookie**.
For **getting all cookies** we can use this : 
```fortran
type(string_type), allocatable :: cookie_keys
type(cookie_type) :: cookie
integer :: i
cookie_list = response%cookies%keys()
do i = 1, size(cookie_list)
   cookie = response%cookies%value(cookie_list(i))
   print *, cookie%name
   print *, cookie%value
   print *, cookie% path
   print *, cookie%expires
   print *, cookie%, domain 
end do
```
I would like to hear your thoughts and suggestions on this approach.

**Comment by milancurcic** [comment]
Do cookies have a use outside of web browsers? My understanding is that it boils down to the server sending a response header that includes one or more `Set-Cookie` fields. So if a user needed to do something with this information, they could, and this capability is already supported via response and header types.

**Comment by interkosmos** [comment]
> Do cookies have a use outside of web browsers?

Some web services use them for token-based authentication.

**Comment by milancurcic** [comment]
Thanks, Philipp. I guess my question is whether we need a dedicated type for cookies if we can already handle response headers.

**Comment by interkosmos** [comment]
> I guess my question is whether we need a dedicated type for cookies if we can already handle response headers.

A dedicated type would make reading and writing easier, in case this feature is desired (as it requires some effort to implement). But maybe not of high priority now.

**Comment by rajkumardongre** [comment]
As we are using a `hash map` to store headers, only one cookie can be stored at a time with the `set-cookie` key. To work around this, for now, considering this feature at low priority, can we store all `set-cookie` headers in a character string separated by a new line character. This way, we can add a `cookies` property of type character string to our `response_type`. To access the `cookies`, we can use the `response%cookies` syntax.
```fortran
character(:), allocatable :: response_cookies
response_cookies = response%cookies
print *, response_cookies
```
Output
```
cookie_1=value_1
cookie_2=value_2
cookie_3=value_3
```

**Comment by milancurcic** [comment]
I see, that makes sense. I didn't think about the fact that a response can have multiple headers with the same key and hashmap doesn't allow that. It seems to me that a hashmap is probably not a good structure for this then. I'm concerned that we'd be introducing a new type (or storing multiple headers as one string) only to work around a limitation of an implementation upstream in the type hierarchy.

What if we had something as simple as

```fortran
type :: header_type
  character(:), allocatable :: key, val
end type header_type
```

and in `response_type` you'd have:

```fortran
type :: response_type
  ...
  type(header_type), allocatable :: headers(:)
  ...
end type response_type
```

Example program

```fortran
program p

  type :: header_type
    character(:), allocatable :: key, val
  end type header_type

  type(header_type), allocatable :: headers(:)

  headers = [ &
    header_type('Content-Length', '123'), &
    header_type('Another-One', 'Hello'), &
    header_type('Set-Cookie', 'Theme-Light'), &
    header_type('Set-Cookie', 'Auth-Token: 1234') &
  ]

  do n = 1, size(headers)
    print '(a, ": ", a)', headers(n)%key, headers(n)%val 
  end do

end program p
```

Output:

```
Content-Length: 123
Another-One: Hello
Set-Cookie: Theme-Light
Set-Cookie: Auth-Token: 1234
```

**Comment by rajkumardongre** [comment]
Thanks, @milancurcic, I have some concerns regarding this approach. For instance, what if the server mistakenly responds with two headers having the same header name other than `Set-Cookie`?
```fortran
 do n = 1, size(headers)
    print '(a, ": ", a)', headers(n)%key, headers(n)%val 
  end do
```
Output :
```
Content-Length: 123
name: sam
name: joe
Set-Cookie: Theme-Light
Set-Cookie: Auth-Token: 1234
```
In this case, if I want to retrieve the header with the name `name`, there will be confusion as we can either get `"sam"` or `"joe"`.

Upon investigating the behavior of the **Python `requests` library**, I discovered that headers are stored in a `dictionary`. If the server responds with two headers having the same name, the library **considers the value of the last header in the sequence**. As for the **`Set-Cookie` header, it appends the cookie strings one after the other**.

To test this behavior, I have created an Express server in Nodejs:
```javascript
const express = require('express')
const app = express()
app.get('/', (req, res) => {
    res.setHeader('name', 'Sam')
    res.setHeader('name', 'Joe')

    res.cookie('cookie_1', 'value_1');
    res.cookie('myCookie', 'myValue', {
        expires: new Date(Date.now() + 900000), // cookie will expire in 15 minutes
        httpOnly: true, 
        secure: true, 
        sameSite: 'strict',
    });
    return res.status(200).json({"hello" : "world"})
});
const port = 3002;
app.listen(process.env.PORT || port, console.log(`Listening on port ${port}`));
``` 
Here is a Python code snippet using the requests library to make a request to the server:
```python
import requests
response = requests.get('http://localhost:3002/')
headers = response.headers
print(headers)
```
The output of the above code is:
```
{
    'X-Powered-By': 'Express',
    'name': 'Joe',
    'Set-Cookie': 'cookie_1=value_1; Path=/, myCookie=myValue; Path=/; Expires=Thu, 08 Jun 2023 16:52:25 GMT; HttpOnly; Secure; SameSite=Strict',
    'Content-Type': 'application/json; charset=utf-8',
    'Content-Length': '17',
    'ETag': 'W/"11-IkjuL6CqqtmReFMfkkvwC0sKj04"',
    'Date': 'Thu, 08 Jun 2023 16:37:25 GMT',
    'Connection': 'keep-alive',
    'Keep-Alive': 'timeout=5'
}
```
In this response, we can see that the `name` header is set to **'Joe'**, which is the value of the last header in the sequence. The `Set-Cookie` header contains both cookies and their values, separated by commas.

**Comment by milancurcic** [comment]
> For instance, what if the server mistakenly responds with two headers having the same header name other than Set-Cookie?

It's an invalid response, but I'd simply let there be duplicate fields if the server sends duplicate fields. The user can then decide how to handle that.

**Comment by rajkumardongre** [comment]
Okay, I will begin implementing these changes. Additionally, I also think that these modifications will help improve the users' ability to manage headers and offer increased flexibility

**Comment by rajkumardongre** [comment]
The issue has been resolved because cookies can be stored in the header alone.
