### ISSUE TITLE
API for POST method request

### ISSUE THREAD

**Issue by rajkumardongre** [fortran-lang/http-client#24]
Before moving forward with the `POST` request API, I have some questions regarding headers. Specifically, I'm curious if there is a need to establish a process for obtaining header values based on their names. I've already created a [pull request](https://github.com/fortran-lang/http-client/pull/25) that includes this functionality, but it will only be merged if it's necessary. Furthermore, I'd like to verify if there are any outstanding tasks associated with the `GET` request.

**Comment by milancurcic** [comment]
Here's the MDN reference for the POST method: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST

How do you think we should expand the `request` API to allow for:

1. URL encoded form data via `application/x-www-form-urlencoded` content type
2. Binary data via `multipart/form-data` content type

Python `requests` distinguishes this based on the type of input to the `data` argument. I.e. if `data` is a `dict`, it's a URL form encoded (IIRC). If it's a `bytes` or `file` object, it goes as `multipart/form-data`.  

We could take a similar approach, i.e. control the request content type based on the type of the `data` input argument.

While this is all most useful with `POST` requests, it applies to all other request methods, e.g. it's possible to send data in the body of a `GET` request, although normally servers should ignore such data.

**Comment by rajkumardongre** [comment]
Thanks @milancurcic , I also go through the request library. In the requests library, data can be passed to an HTTP request using the `data`, `json`, and `files` parameters. 

Here's how each of these parameters works internally:

- **`data`**: The data parameter is used to pass form-encoded data to an HTTP request. When the data parameter is passed, the `Content-Type` header is automatically set to **`application/x-www-form-urlencoded`**. The data is then encoded as a URL-encoded string and added to the request body.

- **`json`**: The json parameter is used to pass JSON-encoded data to an HTTP request. When the json parameter is passed, the `Content-Type` header is automatically set to **`application/json`**. The data is then encoded as a JSON string and added to the request body.
 
- **`files`**: The files parameter is used to upload one or more files to an HTTP request. When the files parameter is passed, the `Content-Type` header is automatically set to **`multipart/form-data`**. The data is then encoded as a multipart form-data and added to the request body along with the files.
 

These parameters can be used together in the same HTTP request. 

- If both the **data and json** parameters are passed, the json parameter takes precedence and the data is encoded as a JSON string. 

- If both the **data and files** parameters are passed, the files parameter takes precedence and the data is encoded as a multipart form-data along with the files.

- Sending both **json and files** in the same request can result in an invalid or ambiguous Content-Type header, which can cause errors or unexpected behavior on the server.

**Comment by rajkumardongre** [comment]
We can adopt a similar approach for our HTTP requests by defining three parameters: `json`, `data`, and `files`. The `json` parameter would be of type string, while the `files` parameter would be an array of `file_type` objects. Additionally, the `data` parameter would be an array of `pair_type` objects to hold key-value pairs of data.

To define the `file_type` object, we can use the following code:
```fortran
type :: file_type
  character(:), allocatable :: form_field, file_path
end type file_type
```
This `file_type` object has two variables: `form_field` and `file_path`. `form_field` would be the name of the form field we want to send the file as, while `file_path` would store the path of the file we want to send.

To define the `pair_type` object, we can use the following code:
```fortran
type :: pair_type
  character(:), allocatable :: key, value
end type pair_type
```
When using the `data` parameter in the request, we need to ensure that the key-value pairs are **URL-encoded**. We can use the `curl_easy_escape` function in libcurl to encode these strings.

Finally, we can define a `request_type` object with three variables: `json`, `data`, and `files`. The data variable would be an array of `pair_type` objects, while json and files would be of type string and an array of `file_type` objects, respectively. Here's the code:
```fortran
type :: request_type
  character(:), allocatable :: json
  type(pair_type), allocatable :: data(:)
  type(file_type), allocatable :: files(:)
  ! other variables below...
end type request_type
```

**Comment by rajkumardongre** [comment]
Based on the discussion from our last meeting, we have agreed to use a `request_type` object with three variables for sending data: `data`, `form`, and `file`.

The `data` variable will be a string type that can be used to send various types of content such as JSON, text, binary data, etc. By default, no` Content-Type` header will be set, so the client must provide the` Content-Type` header themselves.

The `form` variable will be an array of `pair_type` objects used to send **`form-encoded`** data. When using the `data` argument, the `Content-Type` header will automatically be set to **`application/x-www-form-urlencoded`**.

The `file` variable will be of type `pair_type` used to send files. When using the files argument, the `Content-Type` header will be set to **`multipart/form-data`**.

Please let me know if there is anything I may have overlooked or misunderstood, or if you have any other ideas that you would like to share.

**Comment by rajkumardongre** [comment]
I have submitted a [PR](https://github.com/fortran-lang/http-client/pull/32) that adds functionality to support sending `form` data in HTTP requests. Additionally, I have included an example that demonstrates how to send form data using this new functionality

**Comment by rajkumardongre** [comment]
I have tested `PUT`, `PATCH`, and `DELETE` methods and they are functioning properly without the need of any additional setup.

**Comment by milancurcic** [comment]
That's good, but you haven't actually added these tests to the test suite. Having them there will give us assurance that they continue to work as we make changes to the library. I'll open a separate issue.
