### ISSUE TITLE
HTTP Authentication

### ISSUE THREAD

**Issue by interkosmos** [fortran-lang/http-client#37]
HTTP authentication should be easy to add. For example, HTTP Basic Authentication may look like:

```
rc = curl_easy_setopt(curl_ptr, CURLOPT_HTTPAUTH, CURLAUTH_BASIC)
rc = curl_easy_setopt(curl_ptr, CURLOPT_USERNAME, username)
rc = curl_easy_setopt(curl_ptr, CURLOPT_PASSWORD, password)
```

The auth method, user name, and password have to be added to the data model.

**Comment by rajkumardongre** [comment]
Thank you @interkosmos, I will add it.

**Comment by rajkumardongre** [comment]
Hi, I have added authentication option in this [PR](https://github.com/fortran-lang/http-client/pull/44)
