### ISSUE TITLE
Custom HTTP user agent

### ISSUE THREAD

**Issue by interkosmos** [fortran-lang/http-client#38]
Perhaps, a custom HTTP user agent could be added:

```
rc = curl_easy_setopt(curl_ptr, CURLOPT_USERAGENT, 'http-client 1.0')
```

(The version number probably shouldn’t be hard-coded.) Additionally, the user may be allowed to overwrite the user agent. Any thoughts?

**Comment by rajkumardongre** [comment]
Thanks, @interkosmos for the suggestion. I totally agree that users should have full freedom for changing their `user-agent` header, and this is how we are achieving it in http_client.f90 file while setting request headers : 
```fortran
! Set request header
        if (present(header)) then
            request%header = header
            ! Set default request headers.
            if (.not. pair_has_name(header, 'user-agent')) then
              call append_pair(request%header, 'user-agent', 'fortran-http/0.1.0')
            end if
        else
            request%header = [pair_type('user-agent', 'fortran-http/0.1.0')]
        end if
```
here we are 1st checking whether the user has provided headers or not, if there are no headers provided by the user, then we will set only one default header(user-agent), if headers are provided by user then 1st we are checking whether `user-agent` header is already provided by the user or not, using `pair_has_name` function, which will return `true` if `user-agent` is present else `false`.

This is also demonstrated in the `response_header` example where we are setting our own `user-agent` header.

```fortran
! Storing request header in array of pair_type object, where each pair_type
    ! object represents a single header. (in header-name,header-value format)
    req_header = [ &
      pair_type('Another-One', 'Hello'), &
      pair_type('Set-Cookie', 'Theme-Light'), &
      pair_type('Set-Cookie', 'Auth-Token: 12345'), &
      pair_type('User-Agent', 'my user agent') &
    ]

    response = request(url='https://httpbin.org/get', header=req_header)
```

**Comment by rajkumardongre** [comment]
Regarding version number, I agree that currently, we have hard-coded the version number, one solution that I can think of is having a variable `http_version` inside `http_client` module and using this variable to set the version number.
```fortran
module http_client
    implicit none
    private 
    character(:), allocatable :: http_version
    http_version = '0.1.0'
    request%header = [pair_type('user-agent', 'fortran-http/' // http_version)]
end module http_client
```

**Comment by interkosmos** [comment]
Why not turn the version number into a module parameter?

**Comment by rajkumardongre** [comment]
Yes, we can make it parameter, so if i understand well, the updated code would be something like this : 
```fortran
module http_client
    implicit none
    private 
    character(*), parameter :: http_version = '0.1.0'
    request%header = [pair_type('user-agent', 'fortran-http/' // http_version)]
end module http_client
```

**Comment by rajkumardongre** [comment]
I have made the discussed changes in this [PR](https://github.com/fortran-lang/http-client/pull/47).

**Comment by rajkumardongre** [comment]
I am closing this because changes have been made [here](https://github.com/fortran-lang/http-client/commit/291e2ef279aa561fd4db299325de82f293766933).
