### ISSUE TITLE
Complete API docs with FORD

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/http-client#39]
* [x] Complete the docstrings in all source files using the FORD syntax
* [x] Add the ford.md to the repo and ensure the docs site builds correctly
* [x] Add docs build and deployment to GH Pages using GH Actions
* [x] Serve the docs on the http-client.fortran-lang.org subdomain

**Comment by rajkumardongre** [comment]
Hello, I have submitted a pull request (#51) that contains FORD documentation for `http_client`. I would appreciate it if you could review the changes.

**Comment by rajkumardongre** [comment]
Added API docs deployment to GH Pages using GH Actions at #57
