### ISSUE TITLE
Real-world example program

### ISSUE THREAD

**Issue by interkosmos** [fortran-lang/http-client#46]
I’d like to propose a port of [fortran-xkcd](https://github.com/interkosmos/fortran-xkcd) to *http-client* as a “real-world” example. The upstream version uses *fortran-curl* for all GET requests. The fork could replace *fortran-curl* with *http-client* to fetch JSON data and PNG images.

(However, it doesn’t have to be a fork; an example program within *http-client* would be fine, too.)

**Comment by rajkumardongre** [comment]
Thank you @interkosmos, for providing this, I will work on this.

**Comment by rajkumardongre** [comment]
Hi @interkosmos, as suggested I have created a [PR](https://github.com/interkosmos/fortran-xkcd/pull/2), Where I have used `http-client` package to make `http` requests and fetch `json` and `image` data.

**Comment by interkosmos** [comment]
Your changes have been merged. Thank you.
