### ISSUE TITLE
Include github-org-analyzer under tutorial/github-org-analyzer

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/http-client#54]
@rajkumardongre I noticed that the github-org-analyzer project is in a separate repo: https://github.com/rajkumardongre/github-org-analyzer

What do you think about including it under http-client repo in tutorial/github-org-analyzer directory? I think it would helpful to have the full code there, and maintain it under http-client.

**Comment by rajkumardongre** [comment]
Yes, that sounds promising. I will proceed with making the necessary changes.

**Comment by rajkumardongre** [comment]
Added in #56
