### ISSUE TITLE
Release v0.1.0?

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/http-client#55]
I think the repo is in a good place for a first release. What do you think @rajkumardongre @interkosmos?

If you agree, @rajkumardongre, can you please create a new release on GitHub?

* Git tag should be `v0.1.0`
* Release name should be `http-client-0.1.0`

Then we can advertise it on Discourse, Twitter, and HN.

**Comment by rajkumardongre** [comment]
I agree with you @milancurcic, However, I've observed a few minor typographical errors in both the README and Tutorial pages. Once these changes are made, we can proceed with the release.

**Comment by rajkumardongre** [comment]
I believe that once the recent Pull Request is merged, we will be able to release it.

**Comment by milancurcic** [comment]
@rajkumardongre done, you can go ahead!

**Comment by rajkumardongre** [comment]
As this is my first time releasing a project on GitHub, I would appreciate your feedback on the release description. Does it look good to you?
Also there is a "generate release notes" button, should I leave it as it is ?
![image](https://github.com/fortran-lang/http-client/assets/77038993/f3cd749e-24ff-4096-90f2-99a3a0d62463)

**Comment by milancurcic** [comment]
Yes, use generate release notes and add any custom message you want on top (e.g. acknowledging GSoC etc.). Otherwise it looks good.

**Comment by rajkumardongre** [comment]
Done publish the Release 👏

**Comment by milancurcic** [comment]
Great, thank you! Can you please post it on Discourse (in its own new topic and use the Announcements tag) so more people become aware of it and hopefully try it? Will close this issue now.
