### ISSUE TITLE
Organize the source code in modules

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/http-client#7]
See https://github.com/fortran-lang/http-client/pull/5#issuecomment-1562962382.

Let's stick with .f90 for now until VS Code allows overriding defaults.

**Comment by rajkumardongre** [comment]
Alright, I am currently planning to tackle this particular issue, and once it's done, I will shift my focus to the other two([Address remarks by @interkosmos ](https://github.com/fortran-lang/http-client/issues/8) and [Write a few tests for the GET request ](https://github.com/fortran-lang/http-client/issues/9)) issues. Would that be alright?

**Comment by rajkumardongre** [comment]
Hello, I have successfully migrated the code of the `http-client.f90` file into `http.f90`, `http_request.f90`, `http_response.f90`, and `http_client.f90`, and also added a `simple_get` example to demonstrate the working of high level API, to make GET request, in this [PR](https://github.com/fortran-lang/http-client/pull/10).

**Comment by milancurcic** [comment]
Done by #10
