### ISSUE TITLE
Write a few tests for the GET request

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/http-client#9]
Let's write a few tests. For example for the GET request that you make in the example to the mock REST endpoint, you can test that all internal properties of the response are as expected.

**Comment by milancurcic** [comment]
@rajkumardongre let's focus on this next. Now that you have both GET request and header parsing, you can write tests for both. I suggest one program per test suite each, and place them in `test/`. `fpm test` will pick them up automatically. Don't worry about testing frameworks yet. See an example of a frameworkless test program here: https://github.com/modern-fortran/neural-fortran/blob/main/test/test_dense_layer.f90.

**Comment by rajkumardongre** [comment]
Thanks @milancurcic, I will take some inspiration from https://github.com/modern-fortran/neural-fortran/blob/main/test/test_dense_layer.f90. and add some required tests

**Comment by milancurcic** [comment]
Done by #13
